/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package merabriar_core */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 19 "main.go"

#include <stdlib.h>
#include <stdint.h>
#include <string.h>

// Key bundle structure for FFI
typedef struct {
    char* identity_public_key;
    char* signed_prekey;
    char* signature;
    int error;
    char* error_message;
} KeyBundleResult;

// Byte array for encrypted data
typedef struct {
    uint8_t* data;
    int length;
    int error;
    char* error_message;
} ByteArrayResult;

// String result
typedef struct {
    char* data;
    int error;
    char* error_message;
} StringResult;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) int InitCore(char* dbPath, char* encryptionKey);
extern __declspec(dllexport) KeyBundleResult GenerateIdentityKeys(void);
extern __declspec(dllexport) char* GetPublicKeyBundle(void);
extern __declspec(dllexport) int InitSession(char* recipientId, char* keysJson);
extern __declspec(dllexport) int HasSession(char* recipientId);
extern __declspec(dllexport) ByteArrayResult EncryptMessage(char* recipientId, char* plaintext);
extern __declspec(dllexport) StringResult DecryptMessage(char* senderId, uint8_t* ciphertext, int length);
extern __declspec(dllexport) int QueueMessage(char* messageJson);
extern __declspec(dllexport) char* GetQueuedMessages(void);
extern __declspec(dllexport) int ClearQueue(char* idsJson);
extern __declspec(dllexport) int StoreMessage(char* messageJson);
extern __declspec(dllexport) char* GetMessages(char* conversationId, int limit, int offset);
extern __declspec(dllexport) void FreeCString(char* s);
extern __declspec(dllexport) void FreeBytes(uint8_t* data);

#ifdef __cplusplus
}
#endif
