// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  

                  @protected String dco_decode_String(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected KeyBundleDto dco_decode_key_bundle_dto(dynamic raw);

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

@protected PublicKeyBundleDto dco_decode_public_key_bundle_dto(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected KeyBundleDto sse_decode_key_bundle_dto(SseDeserializer deserializer);

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

@protected PublicKeyBundleDto sse_decode_public_key_bundle_dto(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected String cst_encode_String(String raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw; }

@protected JSAny cst_encode_key_bundle_dto(KeyBundleDto raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_list_prim_u_8_strict(raw.identityPublicKey),cst_encode_list_prim_u_8_strict(raw.signedPrekey),cst_encode_list_prim_u_8_strict(raw.signature)].jsify()!; }

@protected JSAny cst_encode_list_prim_u_8_loose(List<int> raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw.jsify()!; }

@protected JSAny cst_encode_list_prim_u_8_strict(Uint8List raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw.jsify()!; }

@protected JSAny? cst_encode_opt_list_prim_u_8_strict(Uint8List? raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw == null ? null : cst_encode_list_prim_u_8_strict(raw); }

@protected JSAny cst_encode_public_key_bundle_dto(PublicKeyBundleDto raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_list_prim_u_8_strict(raw.identityPublicKey),cst_encode_list_prim_u_8_strict(raw.signedPrekey),cst_encode_list_prim_u_8_strict(raw.signature),cst_encode_opt_list_prim_u_8_strict(raw.oneTimePrekey)].jsify()!; }

@protected bool cst_encode_bool(bool raw);

@protected int cst_encode_u_8(int raw);

@protected void cst_encode_unit(void raw);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_key_bundle_dto(KeyBundleDto self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_opt_list_prim_u_8_strict(Uint8List? self, SseSerializer serializer);

@protected void sse_encode_public_key_bundle_dto(PublicKeyBundleDto self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);
                }
                


// Section: wire_class

class RustLibWire implements BaseWire {
            RustLibWire.fromExternalLibrary(ExternalLibrary lib);

            void wire__crate__api__decrypt_message(NativePortType port_,String sender_id,JSAny ciphertext) => wasmModule.wire__crate__api__decrypt_message(port_,sender_id,ciphertext);

void wire__crate__api__encrypt_message(NativePortType port_,String recipient_id,String plaintext) => wasmModule.wire__crate__api__encrypt_message(port_,recipient_id,plaintext);

void wire__crate__api__generate_identity_keys(NativePortType port_) => wasmModule.wire__crate__api__generate_identity_keys(port_);

void wire__crate__api__get_public_key_bundle(NativePortType port_) => wasmModule.wire__crate__api__get_public_key_bundle(port_);

void wire__crate__api__has_session(NativePortType port_,String recipient_id) => wasmModule.wire__crate__api__has_session(port_,recipient_id);

void wire__crate__api__init_core(NativePortType port_,String db_path,String encryption_key) => wasmModule.wire__crate__api__init_core(port_,db_path,encryption_key);

void wire__crate__api__init_session(NativePortType port_,String recipient_id,JSAny identity_public_key,JSAny signed_prekey,JSAny signature,JSAny? one_time_prekey) => wasmModule.wire__crate__api__init_session(port_,recipient_id,identity_public_key,signed_prekey,signature,one_time_prekey);
        }
        @JS('wasm_bindgen') external RustLibWasmModule get wasmModule;

        @JS() @anonymous extension type RustLibWasmModule._(JSObject _) implements JSObject {
            external void wire__crate__api__decrypt_message(NativePortType port_,String sender_id,JSAny ciphertext);

external void wire__crate__api__encrypt_message(NativePortType port_,String recipient_id,String plaintext);

external void wire__crate__api__generate_identity_keys(NativePortType port_);

external void wire__crate__api__get_public_key_bundle(NativePortType port_);

external void wire__crate__api__has_session(NativePortType port_,String recipient_id);

external void wire__crate__api__init_core(NativePortType port_,String db_path,String encryption_key);

external void wire__crate__api__init_session(NativePortType port_,String recipient_id,JSAny identity_public_key,JSAny signed_prekey,JSAny signature,JSAny? one_time_prekey);
        }
        