// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 892831583;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'merabriar_core',
    ioDirectory: '../rust_core/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiDecryptMessage(
      {required String senderId, required List<int> ciphertext});

  Future<Uint8List> crateApiEncryptMessage(
      {required String recipientId, required String plaintext});

  Future<KeyBundleDto> crateApiGenerateIdentityKeys();

  Future<PublicKeyBundleDto> crateApiGetPublicKeyBundle();

  Future<bool> crateApiHasSession({required String recipientId});

  Future<void> crateApiInitCore(
      {required String dbPath, required String encryptionKey});

  Future<void> crateApiInitSession(
      {required String recipientId,
      required List<int> identityPublicKey,
      required List<int> signedPrekey,
      required List<int> signature,
      Uint8List? oneTimePrekey});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiDecryptMessage(
      {required String senderId, required List<int> ciphertext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(senderId);
        var arg1 = cst_encode_list_prim_u_8_loose(ciphertext);
        return wire.wire__crate__api__decrypt_message(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiDecryptMessageConstMeta,
      argValues: [senderId, ciphertext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDecryptMessageConstMeta => const TaskConstMeta(
        debugName: "decrypt_message",
        argNames: ["senderId", "ciphertext"],
      );

  @override
  Future<Uint8List> crateApiEncryptMessage(
      {required String recipientId, required String plaintext}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(recipientId);
        var arg1 = cst_encode_String(plaintext);
        return wire.wire__crate__api__encrypt_message(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_prim_u_8_strict,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiEncryptMessageConstMeta,
      argValues: [recipientId, plaintext],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEncryptMessageConstMeta => const TaskConstMeta(
        debugName: "encrypt_message",
        argNames: ["recipientId", "plaintext"],
      );

  @override
  Future<KeyBundleDto> crateApiGenerateIdentityKeys() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__generate_identity_keys(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_key_bundle_dto,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiGenerateIdentityKeysConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGenerateIdentityKeysConstMeta =>
      const TaskConstMeta(
        debugName: "generate_identity_keys",
        argNames: [],
      );

  @override
  Future<PublicKeyBundleDto> crateApiGetPublicKeyBundle() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__get_public_key_bundle(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_public_key_bundle_dto,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiGetPublicKeyBundleConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGetPublicKeyBundleConstMeta => const TaskConstMeta(
        debugName: "get_public_key_bundle",
        argNames: [],
      );

  @override
  Future<bool> crateApiHasSession({required String recipientId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(recipientId);
        return wire.wire__crate__api__has_session(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiHasSessionConstMeta,
      argValues: [recipientId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiHasSessionConstMeta => const TaskConstMeta(
        debugName: "has_session",
        argNames: ["recipientId"],
      );

  @override
  Future<void> crateApiInitCore(
      {required String dbPath, required String encryptionKey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(dbPath);
        var arg1 = cst_encode_String(encryptionKey);
        return wire.wire__crate__api__init_core(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiInitCoreConstMeta,
      argValues: [dbPath, encryptionKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitCoreConstMeta => const TaskConstMeta(
        debugName: "init_core",
        argNames: ["dbPath", "encryptionKey"],
      );

  @override
  Future<void> crateApiInitSession(
      {required String recipientId,
      required List<int> identityPublicKey,
      required List<int> signedPrekey,
      required List<int> signature,
      Uint8List? oneTimePrekey}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(recipientId);
        var arg1 = cst_encode_list_prim_u_8_loose(identityPublicKey);
        var arg2 = cst_encode_list_prim_u_8_loose(signedPrekey);
        var arg3 = cst_encode_list_prim_u_8_loose(signature);
        var arg4 = cst_encode_opt_list_prim_u_8_strict(oneTimePrekey);
        return wire.wire__crate__api__init_session(
            port_, arg0, arg1, arg2, arg3, arg4);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiInitSessionConstMeta,
      argValues: [
        recipientId,
        identityPublicKey,
        signedPrekey,
        signature,
        oneTimePrekey
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitSessionConstMeta => const TaskConstMeta(
        debugName: "init_session",
        argNames: [
          "recipientId",
          "identityPublicKey",
          "signedPrekey",
          "signature",
          "oneTimePrekey"
        ],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  KeyBundleDto dco_decode_key_bundle_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return KeyBundleDto(
      identityPublicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      signedPrekey: dco_decode_list_prim_u_8_strict(arr[1]),
      signature: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  PublicKeyBundleDto dco_decode_public_key_bundle_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PublicKeyBundleDto(
      identityPublicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      signedPrekey: dco_decode_list_prim_u_8_strict(arr[1]),
      signature: dco_decode_list_prim_u_8_strict(arr[2]),
      oneTimePrekey: dco_decode_opt_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  KeyBundleDto sse_decode_key_bundle_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_identityPublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_signedPrekey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_signature = sse_decode_list_prim_u_8_strict(deserializer);
    return KeyBundleDto(
        identityPublicKey: var_identityPublicKey,
        signedPrekey: var_signedPrekey,
        signature: var_signature);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PublicKeyBundleDto sse_decode_public_key_bundle_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_identityPublicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_signedPrekey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_signature = sse_decode_list_prim_u_8_strict(deserializer);
    var var_oneTimePrekey = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return PublicKeyBundleDto(
        identityPublicKey: var_identityPublicKey,
        signedPrekey: var_signedPrekey,
        signature: var_signature,
        oneTimePrekey: var_oneTimePrekey);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_key_bundle_dto(KeyBundleDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.identityPublicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.signedPrekey, serializer);
    sse_encode_list_prim_u_8_strict(self.signature, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_public_key_bundle_dto(
      PublicKeyBundleDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.identityPublicKey, serializer);
    sse_encode_list_prim_u_8_strict(self.signedPrekey, serializer);
    sse_encode_list_prim_u_8_strict(self.signature, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.oneTimePrekey, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
