// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  KeyBundleDto dco_decode_key_bundle_dto(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PublicKeyBundleDto dco_decode_public_key_bundle_dto(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  KeyBundleDto sse_decode_key_bundle_dto(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PublicKeyBundleDto sse_decode_public_key_bundle_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_encode_list_prim_u_8_loose(
      List<int> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_loose(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
      Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
      cst_encode_opt_list_prim_u_8_strict(Uint8List? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_list_prim_u_8_strict(raw);
  }

  @protected
  void cst_api_fill_to_wire_key_bundle_dto(
      KeyBundleDto apiObj, wire_cst_key_bundle_dto wireObj) {
    wireObj.identity_public_key =
        cst_encode_list_prim_u_8_strict(apiObj.identityPublicKey);
    wireObj.signed_prekey =
        cst_encode_list_prim_u_8_strict(apiObj.signedPrekey);
    wireObj.signature = cst_encode_list_prim_u_8_strict(apiObj.signature);
  }

  @protected
  void cst_api_fill_to_wire_public_key_bundle_dto(
      PublicKeyBundleDto apiObj, wire_cst_public_key_bundle_dto wireObj) {
    wireObj.identity_public_key =
        cst_encode_list_prim_u_8_strict(apiObj.identityPublicKey);
    wireObj.signed_prekey =
        cst_encode_list_prim_u_8_strict(apiObj.signedPrekey);
    wireObj.signature = cst_encode_list_prim_u_8_strict(apiObj.signature);
    wireObj.one_time_prekey =
        cst_encode_opt_list_prim_u_8_strict(apiObj.oneTimePrekey);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_key_bundle_dto(KeyBundleDto self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_public_key_bundle_dto(
      PublicKeyBundleDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
    'store_dart_post_cobject',
  );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__decrypt_message(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sender_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> ciphertext,
  ) {
    return _wire__crate__api__decrypt_message(port_, sender_id, ciphertext);
  }

  late final _wire__crate__api__decrypt_messagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )>>('frbgen_merabriar_wire__crate__api__decrypt_message');
  late final _wire__crate__api__decrypt_message =
      _wire__crate__api__decrypt_messagePtr.asFunction<
          void Function(
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
          )>();

  void wire__crate__api__encrypt_message(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> recipient_id,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> plaintext,
  ) {
    return _wire__crate__api__encrypt_message(port_, recipient_id, plaintext);
  }

  late final _wire__crate__api__encrypt_messagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_merabriar_wire__crate__api__encrypt_message');
  late final _wire__crate__api__encrypt_message =
      _wire__crate__api__encrypt_messagePtr.asFunction<
          void Function(
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  void wire__crate__api__generate_identity_keys(int port_) {
    return _wire__crate__api__generate_identity_keys(port_);
  }

  late final _wire__crate__api__generate_identity_keysPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_merabriar_wire__crate__api__generate_identity_keys',
  );
  late final _wire__crate__api__generate_identity_keys =
      _wire__crate__api__generate_identity_keysPtr
          .asFunction<void Function(int)>();

  void wire__crate__api__get_public_key_bundle(int port_) {
    return _wire__crate__api__get_public_key_bundle(port_);
  }

  late final _wire__crate__api__get_public_key_bundlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_merabriar_wire__crate__api__get_public_key_bundle',
  );
  late final _wire__crate__api__get_public_key_bundle =
      _wire__crate__api__get_public_key_bundlePtr
          .asFunction<void Function(int)>();

  void wire__crate__api__has_session(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> recipient_id,
  ) {
    return _wire__crate__api__has_session(port_, recipient_id);
  }

  late final _wire__crate__api__has_sessionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_merabriar_wire__crate__api__has_session');
  late final _wire__crate__api__has_session =
      _wire__crate__api__has_sessionPtr.asFunction<
          void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)>();

  void wire__crate__api__init_core(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> db_path,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> encryption_key,
  ) {
    return _wire__crate__api__init_core(port_, db_path, encryption_key);
  }

  late final _wire__crate__api__init_corePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_merabriar_wire__crate__api__init_core');
  late final _wire__crate__api__init_core =
      _wire__crate__api__init_corePtr.asFunction<
          void Function(
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  void wire__crate__api__init_session(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> recipient_id,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> identity_public_key,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signed_prekey,
    ffi.Pointer<wire_cst_list_prim_u_8_loose> signature,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> one_time_prekey,
  ) {
    return _wire__crate__api__init_session(
      port_,
      recipient_id,
      identity_public_key,
      signed_prekey,
      signature,
      one_time_prekey,
    );
  }

  late final _wire__crate__api__init_sessionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_merabriar_wire__crate__api__init_session');
  late final _wire__crate__api__init_session =
      _wire__crate__api__init_sessionPtr.asFunction<
          void Function(
            int,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_loose>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>();

  ffi.Pointer<wire_cst_list_prim_u_8_loose> cst_new_list_prim_u_8_loose(
    int len,
  ) {
    return _cst_new_list_prim_u_8_loose(len);
  }

  late final _cst_new_list_prim_u_8_loosePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(
              ffi.Int32)>>('frbgen_merabriar_cst_new_list_prim_u_8_loose');
  late final _cst_new_list_prim_u_8_loose = _cst_new_list_prim_u_8_loosePtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_loose> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(
              ffi.Int32)>>('frbgen_merabriar_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
    'dummy_method_to_enforce_bundling',
  );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
    DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
    DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType
    = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_prim_u_8_loose extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_key_bundle_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> identity_public_key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> signed_prekey;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> signature;
}

final class wire_cst_public_key_bundle_dto extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> identity_public_key;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> signed_prekey;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> signature;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> one_time_prekey;
}
