// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
non_camel_case_types,
unused,
non_snake_case,
clippy::needless_return,
clippy::redundant_closure_call,
clippy::redundant_closure,
clippy::useless_conversion,
clippy::unit_arg,
clippy::unused_unit,
clippy::double_parens,
clippy::let_and_return,
clippy::too_many_arguments,
clippy::match_single_binding,
clippy::clone_on_copy,
clippy::let_unit_value,
clippy::deref_addrof,
clippy::explicit_auto_deref,
clippy::borrow_deref_ref,
clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
                    default_stream_sink_codec = DcoCodec,
                    default_rust_opaque = RustOpaqueNom,
                    default_rust_auto_opaque = RustAutoOpaqueNom,
                );
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 892831583;
            

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__decrypt_message_impl(port_: flutter_rust_bridge::for_generated::MessagePort,sender_id: impl CstDecode<String>,ciphertext: impl CstDecode<Vec<u8>>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "decrypt_message", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_sender_id = sender_id.cst_decode();let api_ciphertext = ciphertext.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, String>((move ||  {
                         let output_ok = crate::api::decrypt_message(api_sender_id, api_ciphertext)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__encrypt_message_impl(port_: flutter_rust_bridge::for_generated::MessagePort,recipient_id: impl CstDecode<String>,plaintext: impl CstDecode<String>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "encrypt_message", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_recipient_id = recipient_id.cst_decode();let api_plaintext = plaintext.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, String>((move ||  {
                         let output_ok = crate::api::encrypt_message(api_recipient_id, api_plaintext)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__generate_identity_keys_impl(port_: flutter_rust_bridge::for_generated::MessagePort)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "generate_identity_keys", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {  move |context|  {
                    transform_result_dco::<_, _, String>((move ||  {
                         let output_ok = crate::api::generate_identity_keys()?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__get_public_key_bundle_impl(port_: flutter_rust_bridge::for_generated::MessagePort)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "get_public_key_bundle", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {  move |context|  {
                    transform_result_dco::<_, _, String>((move ||  {
                         let output_ok = crate::api::get_public_key_bundle()?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__has_session_impl(port_: flutter_rust_bridge::for_generated::MessagePort,recipient_id: impl CstDecode<String>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "has_session", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_recipient_id = recipient_id.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::has_session(api_recipient_id))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__init_core_impl(port_: flutter_rust_bridge::for_generated::MessagePort,db_path: impl CstDecode<String>,encryption_key: impl CstDecode<String>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "init_core", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_db_path = db_path.cst_decode();let api_encryption_key = encryption_key.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, String>((move ||  {
                         let output_ok = crate::api::init_core(api_db_path, api_encryption_key)?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__init_session_impl(port_: flutter_rust_bridge::for_generated::MessagePort,recipient_id: impl CstDecode<String>,identity_public_key: impl CstDecode<Vec<u8>>,signed_prekey: impl CstDecode<Vec<u8>>,signature: impl CstDecode<Vec<u8>>,one_time_prekey: impl CstDecode<Option<Vec<u8>>>)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "init_session", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { let api_recipient_id = recipient_id.cst_decode();let api_identity_public_key = identity_public_key.cst_decode();let api_signed_prekey = signed_prekey.cst_decode();let api_signature = signature.cst_decode();let api_one_time_prekey = one_time_prekey.cst_decode(); move |context|  {
                    transform_result_dco::<_, _, String>((move ||  {
                         let output_ok = crate::api::init_session(api_recipient_id, api_identity_public_key, api_signed_prekey, api_signature, api_one_time_prekey)?;   Ok(output_ok)
                    })())
                } })
            }

// Section: dart2rust

impl CstDecode<bool> for bool {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> bool {
                self
            }
        }impl CstDecode<u8> for u8 {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> u8 {
                self
            }
        }
                impl SseDecode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();}
                }
                
                impl SseDecode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap() != 0}
                }
                
                impl SseDecode for crate::api::KeyBundleDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_identityPublicKey = <Vec<u8>>::sse_decode(deserializer);
let mut var_signedPrekey = <Vec<u8>>::sse_decode(deserializer);
let mut var_signature = <Vec<u8>>::sse_decode(deserializer);
return crate::api::KeyBundleDto{identity_public_key: var_identityPublicKey, signed_prekey: var_signedPrekey, signature: var_signature};}
                }
                
                impl SseDecode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<u8>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Option<Vec<u8>> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<Vec<u8>>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }
                
                impl SseDecode for crate::api::PublicKeyBundleDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_identityPublicKey = <Vec<u8>>::sse_decode(deserializer);
let mut var_signedPrekey = <Vec<u8>>::sse_decode(deserializer);
let mut var_signature = <Vec<u8>>::sse_decode(deserializer);
let mut var_oneTimePrekey = <Option<Vec<u8>>>::sse_decode(deserializer);
return crate::api::PublicKeyBundleDto{identity_public_key: var_identityPublicKey, signed_prekey: var_signedPrekey, signature: var_signature, one_time_prekey: var_oneTimePrekey};}
                }
                
                impl SseDecode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap()}
                }
                
                impl SseDecode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
                }
                
                impl SseDecode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i32::<NativeEndian>().unwrap()}
                }
                
                fn pde_ffi_dispatcher_primary_impl(
                    func_id: i32,port: flutter_rust_bridge::for_generated::MessagePort,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                )  {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        
                        _ => unreachable!(),
                    }
                }
                
                fn pde_ffi_dispatcher_sync_impl(
                    func_id: i32,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        
                        _ => unreachable!(),
                    }
                }
                

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::KeyBundleDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.identity_public_key.into_into_dart().into_dart(),
self.signed_prekey.into_into_dart().into_dart(),
self.signature.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::KeyBundleDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::KeyBundleDto> for crate::api::KeyBundleDto {
            fn into_into_dart(self) -> crate::api::KeyBundleDto {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::PublicKeyBundleDto {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.identity_public_key.into_into_dart().into_dart(),
self.signed_prekey.into_into_dart().into_dart(),
self.signature.into_into_dart().into_dart(),
self.one_time_prekey.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::PublicKeyBundleDto {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::PublicKeyBundleDto> for crate::api::PublicKeyBundleDto {
            fn into_into_dart(self) -> crate::api::PublicKeyBundleDto {
                self
            }
        }

                impl SseEncode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.into_bytes(), serializer);}
                }
                
                impl SseEncode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self as _).unwrap();}
                }
                
                impl SseEncode for crate::api::KeyBundleDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.identity_public_key, serializer);
<Vec<u8>>::sse_encode(self.signed_prekey, serializer);
<Vec<u8>>::sse_encode(self.signature, serializer);}
                }
                
                impl SseEncode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <u8>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Option<Vec<u8>> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <Vec<u8>>::sse_encode(value, serializer);
                }}
                }
                
                impl SseEncode for crate::api::PublicKeyBundleDto {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.identity_public_key, serializer);
<Vec<u8>>::sse_encode(self.signed_prekey, serializer);
<Vec<u8>>::sse_encode(self.signature, serializer);
<Option<Vec<u8>>>::sse_encode(self.one_time_prekey, serializer);}
                }
                
                impl SseEncode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self).unwrap();}
                }
                
                impl SseEncode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
                }
                
                impl SseEncode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i32::<NativeEndian>(self).unwrap();}
                }
                


        
        
        #[cfg(not(target_family = "wasm"))]
        mod io {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_io!();

// Section: dart2rust

impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> String {
                let vec: Vec<u8> = self.cst_decode(); String::from_utf8(vec).unwrap()
            }
        }impl CstDecode<crate::api::KeyBundleDto> for wire_cst_key_bundle_dto {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::KeyBundleDto {
                crate::api::KeyBundleDto{identity_public_key:  self.identity_public_key.cst_decode(),signed_prekey:  self.signed_prekey.cst_decode(),signature:  self.signature.cst_decode()}
            }
        }impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_loose {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Vec<u8> {
                unsafe {
                    let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                    flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
                }
            }
        }impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Vec<u8> {
                unsafe {
                    let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                    flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
                }
            }
        }impl CstDecode<crate::api::PublicKeyBundleDto> for wire_cst_public_key_bundle_dto {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::PublicKeyBundleDto {
                crate::api::PublicKeyBundleDto{identity_public_key:  self.identity_public_key.cst_decode(),signed_prekey:  self.signed_prekey.cst_decode(),signature:  self.signature.cst_decode(),one_time_prekey:  self.one_time_prekey.cst_decode()}
            }
        }impl NewWithNullPtr for wire_cst_key_bundle_dto {
            fn new_with_null_ptr() -> Self {
                Self { identity_public_key: core::ptr::null_mut(),
signed_prekey: core::ptr::null_mut(),
signature: core::ptr::null_mut(), }
            }
        }
        impl Default for wire_cst_key_bundle_dto {
            fn default() -> Self {
                Self::new_with_null_ptr()
            }
        }impl NewWithNullPtr for wire_cst_public_key_bundle_dto {
            fn new_with_null_ptr() -> Self {
                Self { identity_public_key: core::ptr::null_mut(),
signed_prekey: core::ptr::null_mut(),
signature: core::ptr::null_mut(),
one_time_prekey: core::ptr::null_mut(), }
            }
        }
        impl Default for wire_cst_public_key_bundle_dto {
            fn default() -> Self {
                Self::new_with_null_ptr()
            }
        }

                #[unsafe(no_mangle)]
                pub extern "C" fn frbgen_merabriar_wire__crate__api__decrypt_message(port_: i64, sender_id: *mut wire_cst_list_prim_u_8_strict, ciphertext: *mut wire_cst_list_prim_u_8_loose)  {
                    wire__crate__api__decrypt_message_impl(port_, sender_id, ciphertext)
                }
            

                #[unsafe(no_mangle)]
                pub extern "C" fn frbgen_merabriar_wire__crate__api__encrypt_message(port_: i64, recipient_id: *mut wire_cst_list_prim_u_8_strict, plaintext: *mut wire_cst_list_prim_u_8_strict)  {
                    wire__crate__api__encrypt_message_impl(port_, recipient_id, plaintext)
                }
            

                #[unsafe(no_mangle)]
                pub extern "C" fn frbgen_merabriar_wire__crate__api__generate_identity_keys(port_: i64)  {
                    wire__crate__api__generate_identity_keys_impl(port_)
                }
            

                #[unsafe(no_mangle)]
                pub extern "C" fn frbgen_merabriar_wire__crate__api__get_public_key_bundle(port_: i64)  {
                    wire__crate__api__get_public_key_bundle_impl(port_)
                }
            

                #[unsafe(no_mangle)]
                pub extern "C" fn frbgen_merabriar_wire__crate__api__has_session(port_: i64, recipient_id: *mut wire_cst_list_prim_u_8_strict)  {
                    wire__crate__api__has_session_impl(port_, recipient_id)
                }
            

                #[unsafe(no_mangle)]
                pub extern "C" fn frbgen_merabriar_wire__crate__api__init_core(port_: i64, db_path: *mut wire_cst_list_prim_u_8_strict, encryption_key: *mut wire_cst_list_prim_u_8_strict)  {
                    wire__crate__api__init_core_impl(port_, db_path, encryption_key)
                }
            

                #[unsafe(no_mangle)]
                pub extern "C" fn frbgen_merabriar_wire__crate__api__init_session(port_: i64, recipient_id: *mut wire_cst_list_prim_u_8_strict, identity_public_key: *mut wire_cst_list_prim_u_8_loose, signed_prekey: *mut wire_cst_list_prim_u_8_loose, signature: *mut wire_cst_list_prim_u_8_loose, one_time_prekey: *mut wire_cst_list_prim_u_8_strict)  {
                    wire__crate__api__init_session_impl(port_, recipient_id, identity_public_key, signed_prekey, signature, one_time_prekey)
                }
            

                #[unsafe(no_mangle)]
                pub extern "C" fn frbgen_merabriar_cst_new_list_prim_u_8_loose(len: i32) -> *mut wire_cst_list_prim_u_8_loose {
                    let ans = wire_cst_list_prim_u_8_loose { ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len), len };
                    flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
                }
            

                #[unsafe(no_mangle)]
                pub extern "C" fn frbgen_merabriar_cst_new_list_prim_u_8_strict(len: i32) -> *mut wire_cst_list_prim_u_8_strict {
                    let ans = wire_cst_list_prim_u_8_strict { ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len), len };
                    flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
                }
            
#[repr(C)] #[derive(Clone, Copy)] pub struct wire_cst_key_bundle_dto { identity_public_key: *mut wire_cst_list_prim_u_8_strict,
signed_prekey: *mut wire_cst_list_prim_u_8_strict,
signature: *mut wire_cst_list_prim_u_8_strict }
#[repr(C)] #[derive(Clone, Copy)] pub struct wire_cst_list_prim_u_8_loose { ptr: *mut u8,
len: i32 }
#[repr(C)] #[derive(Clone, Copy)] pub struct wire_cst_list_prim_u_8_strict { ptr: *mut u8,
len: i32 }
#[repr(C)] #[derive(Clone, Copy)] pub struct wire_cst_public_key_bundle_dto { identity_public_key: *mut wire_cst_list_prim_u_8_strict,
signed_prekey: *mut wire_cst_list_prim_u_8_strict,
signature: *mut wire_cst_list_prim_u_8_strict,
one_time_prekey: *mut wire_cst_list_prim_u_8_strict }
        }
        #[cfg(not(target_family = "wasm"))]
        pub use io::*;
        
        
        /// cbindgen:ignore
        #[cfg(target_family = "wasm")]
        mod web {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;
                use flutter_rust_bridge::for_generated::wasm_bindgen;
                use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;


// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_web!();

// Section: dart2rust

impl CstDecode<String> for String {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> String {
                self
            }
        }impl CstDecode<crate::api::KeyBundleDto> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::KeyBundleDto {
                let self_ = self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>().unwrap();
                assert_eq!(self_.length(), 3, "Expected 3 elements, got {}", self_.length());
                crate::api::KeyBundleDto{identity_public_key:  self_.get(0).cst_decode(),signed_prekey:  self_.get(1).cst_decode(),signature:  self_.get(2).cst_decode()}
            }
        }impl CstDecode<Vec<u8>> for Box<[u8]> {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Vec<u8> {
                self.into_vec()
            }
        }impl CstDecode<Option<Vec<u8>>> for Option<Box<[u8]>> {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Option<Vec<u8>> {
                self.map(CstDecode::cst_decode)
            }
        }impl CstDecode<crate::api::PublicKeyBundleDto> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> crate::api::PublicKeyBundleDto {
                let self_ = self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>().unwrap();
                assert_eq!(self_.length(), 4, "Expected 4 elements, got {}", self_.length());
                crate::api::PublicKeyBundleDto{identity_public_key:  self_.get(0).cst_decode(),signed_prekey:  self_.get(1).cst_decode(),signature:  self_.get(2).cst_decode(),one_time_prekey:  self_.get(3).cst_decode()}
            }
        }impl CstDecode<String> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> String {
                self.as_string().expect("non-UTF-8 string, or not a string")
            }
        }impl CstDecode<bool> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> bool {
                self.is_truthy()
            }
        }impl CstDecode<Vec<u8>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> Vec<u8> {
                self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint8Array>().to_vec().into()
            }
        }impl CstDecode<u8> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
            // Codec=Cst (C-struct based), see doc to use other codecs
            fn cst_decode(self) -> u8 {
                self.unchecked_into_f64() as _
            }
        }

                #[wasm_bindgen]
                pub  fn wire__crate__api__decrypt_message(port_: flutter_rust_bridge::for_generated::MessagePort, sender_id: String, ciphertext: Box<[u8]>)  {
                    wire__crate__api__decrypt_message_impl(port_, sender_id, ciphertext)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__encrypt_message(port_: flutter_rust_bridge::for_generated::MessagePort, recipient_id: String, plaintext: String)  {
                    wire__crate__api__encrypt_message_impl(port_, recipient_id, plaintext)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__generate_identity_keys(port_: flutter_rust_bridge::for_generated::MessagePort)  {
                    wire__crate__api__generate_identity_keys_impl(port_)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__get_public_key_bundle(port_: flutter_rust_bridge::for_generated::MessagePort)  {
                    wire__crate__api__get_public_key_bundle_impl(port_)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__has_session(port_: flutter_rust_bridge::for_generated::MessagePort, recipient_id: String)  {
                    wire__crate__api__has_session_impl(port_, recipient_id)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__init_core(port_: flutter_rust_bridge::for_generated::MessagePort, db_path: String, encryption_key: String)  {
                    wire__crate__api__init_core_impl(port_, db_path, encryption_key)
                }
            

                #[wasm_bindgen]
                pub  fn wire__crate__api__init_session(port_: flutter_rust_bridge::for_generated::MessagePort, recipient_id: String, identity_public_key: Box<[u8]>, signed_prekey: Box<[u8]>, signature: Box<[u8]>, one_time_prekey: Option<Box<[u8]>>)  {
                    wire__crate__api__init_session_impl(port_, recipient_id, identity_public_key, signed_prekey, signature, one_time_prekey)
                }
            

        }
        #[cfg(target_family = "wasm")]
        pub use web::*;
        